// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQfUM6EW94u0o-QiETDMEsuTDraOrHkBc',
    appId: '1:665729008040:web:7bde6585c8950c23b39d9d',
    messagingSenderId: '665729008040',
    projectId: 'job-application-tracker-147e9',
    authDomain: 'job-application-tracker-147e9.firebaseapp.com',
    storageBucket: 'job-application-tracker-147e9.firebasestorage.app',
    measurementId: 'G-PDYC6CLCGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO9vcpGCNuEAazd9axAS5Mpjremuk8xCE',
    appId: '1:665729008040:android:364dc74cf30376cdb39d9d',
    messagingSenderId: '665729008040',
    projectId: 'job-application-tracker-147e9',
    storageBucket: 'job-application-tracker-147e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpmgzMWAjeUYDR3NtAnXw0Yux6ZAcao4E',
    appId: '1:665729008040:ios:6bb48b47d158c774b39d9d',
    messagingSenderId: '665729008040',
    projectId: 'job-application-tracker-147e9',
    storageBucket: 'job-application-tracker-147e9.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );
}
